### ISSUE TITLE
System.StackOverflowException thrown on levelprefabs file

### ISSUE THREAD

**Issue by mhoangvslev** [Perfare/UnityStudio#107]
I tried this amazing tool on a game called Verdun. It works for .unity3d files, despite some lower quality in term of lighting on textures.

I attempted to open levelprefabs file and it gave me the following error:

> System.StackOverflowException occurred
>   HResult=0x800703E9
>   Message=Exception of type 'System.StackOverflowException' was thrown.
>   Source=<Cannot evaluate the exception source>

Please find [enclosed](https://drive.google.com/file/d/0B-_4-aq7-akWc0FmSWI0U1hMUnM/view?usp=sharing) the concerned file.

**Comment by Perfare** [comment]
fixed

**Comment by mhoangvslev** [comment]
Did you test with the file I sent? I tested your latest commit and the app still crash.

**Comment by Perfare** [comment]
Select bundle file type to load file

**Comment by mhoangvslev** [comment]
Work like a charm, many thanks!
