### ISSUE TITLE
Animator with selected AnimationClip does not work (crashes)

### ISSUE THREAD

**Issue by Springtraph** [Perfare/UnityStudio#160]
I seriously don't know how to use this feature, i just imported Paladins Strike's data (android) and tried to export an AnimationClip on assets tab
If i select the files related to the animationclip (with animationclip itself) on scene hierarchy it will export the model with correct texture unwrapping with correct mesh but there is no animation.
If i select only animationclip the "Animator with selected AnimationClip" does not do anything (which is normal).
If i select animationclip with an animator, Program crashes
If i select only animator, program still crashes.
How do i use that feature? Any explanations?

**Comment by JuGGerNaunT** [comment]
Provide files which has problems and maybe author or someone else could fix this issue.

**Comment by Springtraph** [comment]
I can provide whole game data if its needed. Which file hosting service do i need to use?

**Comment by Springtraph** [comment]
Also, if I select only an animator based on character I would get detailed animationclips meanwhile at folder import I only get one.

**Comment by Springtraph** [comment]
@Springtraph alright, I uploaded it to my drive folder.
https://drive.google.com/file/d/1TwJCa2wL2Y-A4E4A8TS5gEpCvG92f-CN/view?usp=drivesdk
Make sure to unzip obb using 7-zip

**Comment by mafaca** [comment]
Can you tell name  of file which contains AnimationClip and name of file which contains corresponding Animator? Obb contains 7000 files and it is very hard to find such pair.

**Comment by Springtraph** [comment]
Just filter "Skye" at the assets tab and try to export the only animationclip it shows

**Comment by Springtraph** [comment]
Alright, i got full detailed animationclips but still i cannot export.
Here is the steps

1. Identify animators
I fired up the unity studio then imported whole data, then i filtered the character i wanted to export animations

2.  Save animators somewhere else
I located all of HQ root animators and saved them an above folder
[https://resmim.net/f/ZZd343.png](url)

3. Load only one animator
I reopened unity studio and loaded only one animator file
[https://resmim.net/f/5UbIxK.png](url)

4. Stare at screen and try to guess what to do next
[https://resmim.net/f/WL0HPY.png](url)

It crashed again.

**Comment by mafaca** [comment]
US handles Animatior or AnimationClip incorrectly. Wait for Perfare, maybe he can clarify this moment.

**Comment by Perfare** [comment]
The problem is because Avatar.m_TOS containing the wrong Information
Because of this error, US will get an empty bone name "" and crashes.
I've fixed it, but it tells that shouldn't rely on Avatar information

**Comment by Springtraph** [comment]
Just a question, how do i download the lastest animation branch's build from appveyor?
There are no artifacts.

**Comment by Springtraph** [comment]
Alright thanks.
Shall i open another issue? (Because its still crashing.)
[Picture](https://resmim.net/f/LOH4Iw.png)

**Comment by Springtraph** [comment]
Why animation branch got removed?

**Comment by mafaca** [comment]
Maybe because it has contained company Which Must Not Be Named ;)

**Comment by Perfare** [comment]
@Springtraph I'll soon merge it into master branch.

**Comment by Springtraph** [comment]
Thanks.
PS (emoticons are broken in GitHub)

**Comment by WollieWoltaz** [comment]
Is this still working? Also.. when some animations can get exported are the in such a file format that they can be imported into a modeling program for exaple 3ds Max?

Kind regards,
